<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Laymont\Gdcountries\Models\Country;


class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array(
                "id" => 1,
                "continent_code" => "AS",
                "country_code" => "AF",
                "country_name" => "Afghanistan",
                "alpha_3" => "AFG",
                "phone_code" => "93",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "continent_code" => "EU",
                "country_code" => "AX",
                "country_name" => "Aland Islands",
                "alpha_3" => "ALA",
                "phone_code" => "358",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "continent_code" => "EU",
                "country_code" => "AL",
                "country_name" => "Albania",
                "alpha_3" => "ALB",
                "phone_code" => "355",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "continent_code" => "AF",
                "country_code" => "DZ",
                "country_name" => "Algeria",
                "alpha_3" => "DZA",
                "phone_code" => "213",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "continent_code" => "OC",
                "country_code" => "AS",
                "country_name" => "American Samoa",
                "alpha_3" => "ASM",
                "phone_code" => "1684",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "continent_code" => "EU",
                "country_code" => "AD",
                "country_name" => "Andorra",
                "alpha_3" => "AND",
                "phone_code" => "376",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "continent_code" => "AF",
                "country_code" => "AO",
                "country_name" => "Angola",
                "alpha_3" => "AGO",
                "phone_code" => "244",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "continent_code" => "NA",
                "country_code" => "AI",
                "country_name" => "Anguilla",
                "alpha_3" => "AIA",
                "phone_code" => "1264",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "continent_code" => "AN",
                "country_code" => "AQ",
                "country_name" => "Antarctica",
                "alpha_3" => "ATA",
                "phone_code" => "672",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "continent_code" => "NA",
                "country_code" => "AG",
                "country_name" => "Antigua and Barbuda",
                "alpha_3" => "ATG",
                "phone_code" => "1268",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "continent_code" => "SA",
                "country_code" => "AR",
                "country_name" => "Argentina",
                "alpha_3" => "ARG",
                "phone_code" => "54",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "continent_code" => "AS",
                "country_code" => "AM",
                "country_name" => "Armenia",
                "alpha_3" => "ARM",
                "phone_code" => "374",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "continent_code" => "NA",
                "country_code" => "AW",
                "country_name" => "Aruba",
                "alpha_3" => "ABW",
                "phone_code" => "297",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "continent_code" => "OC",
                "country_code" => "AU",
                "country_name" => "Australia",
                "alpha_3" => "AUS",
                "phone_code" => "61",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "continent_code" => "EU",
                "country_code" => "AT",
                "country_name" => "Austria",
                "alpha_3" => "AUT",
                "phone_code" => "43",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "continent_code" => "AS",
                "country_code" => "AZ",
                "country_name" => "Azerbaijan",
                "alpha_3" => "AZE",
                "phone_code" => "994",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "continent_code" => "NA",
                "country_code" => "BS",
                "country_name" => "Bahamas",
                "alpha_3" => "BHS",
                "phone_code" => "1242",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "continent_code" => "AS",
                "country_code" => "BH",
                "country_name" => "Bahrain",
                "alpha_3" => "BHR",
                "phone_code" => "973",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "continent_code" => "AS",
                "country_code" => "BD",
                "country_name" => "Bangladesh",
                "alpha_3" => "BGD",
                "phone_code" => "880",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "continent_code" => "NA",
                "country_code" => "BB",
                "country_name" => "Barbados",
                "alpha_3" => "BRB",
                "phone_code" => "1246",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "continent_code" => "EU",
                "country_code" => "BY",
                "country_name" => "Belarus",
                "alpha_3" => "BLR",
                "phone_code" => "375",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "continent_code" => "EU",
                "country_code" => "BE",
                "country_name" => "Belgium",
                "alpha_3" => "BEL",
                "phone_code" => "32",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "continent_code" => "NA",
                "country_code" => "BZ",
                "country_name" => "Belize",
                "alpha_3" => "BLZ",
                "phone_code" => "501",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "continent_code" => "AF",
                "country_code" => "BJ",
                "country_name" => "Benin",
                "alpha_3" => "BEN",
                "phone_code" => "229",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "continent_code" => "NA",
                "country_code" => "BM",
                "country_name" => "Bermuda",
                "alpha_3" => "BMU",
                "phone_code" => "1441",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "continent_code" => "AS",
                "country_code" => "BT",
                "country_name" => "Bhutan",
                "alpha_3" => "BTN",
                "phone_code" => "975",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "continent_code" => "SA",
                "country_code" => "BO",
                "country_name" => "Bolivia",
                "alpha_3" => "BOL",
                "phone_code" => "591",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "continent_code" => "NA",
                "country_code" => "BQ",
                "country_name" => "Bonaire, Sint Eustatius and Saba",
                "alpha_3" => "BES",
                "phone_code" => "599",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "continent_code" => "EU",
                "country_code" => "BA",
                "country_name" => "Bosnia and Herzegovina",
                "alpha_3" => "BIH",
                "phone_code" => "387",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "continent_code" => "AF",
                "country_code" => "BW",
                "country_name" => "Botswana",
                "alpha_3" => "BWA",
                "phone_code" => "267",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "continent_code" => "AN",
                "country_code" => "BV",
                "country_name" => "Bouvet Island",
                "alpha_3" => "BVT",
                "phone_code" => "55",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "continent_code" => "SA",
                "country_code" => "BR",
                "country_name" => "Brazil",
                "alpha_3" => "BRA",
                "phone_code" => "55",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "continent_code" => "AS",
                "country_code" => "IO",
                "country_name" => "British Indian Ocean Territory",
                "alpha_3" => "IOT",
                "phone_code" => "246",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "continent_code" => "AS",
                "country_code" => "BN",
                "country_name" => "Brunei Darussalam",
                "alpha_3" => "BRN",
                "phone_code" => "673",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "continent_code" => "EU",
                "country_code" => "BG",
                "country_name" => "Bulgaria",
                "alpha_3" => "BGR",
                "phone_code" => "359",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "continent_code" => "AF",
                "country_code" => "BF",
                "country_name" => "Burkina Faso",
                "alpha_3" => "BFA",
                "phone_code" => "226",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "continent_code" => "AF",
                "country_code" => "BI",
                "country_name" => "Burundi",
                "alpha_3" => "BDI",
                "phone_code" => "257",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "continent_code" => "AS",
                "country_code" => "KH",
                "country_name" => "Cambodia",
                "alpha_3" => "KHM",
                "phone_code" => "855",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "continent_code" => "AF",
                "country_code" => "CM",
                "country_name" => "Cameroon",
                "alpha_3" => "CMR",
                "phone_code" => "237",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "continent_code" => "NA",
                "country_code" => "CA",
                "country_name" => "Canada",
                "alpha_3" => "CAN",
                "phone_code" => "1",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "continent_code" => "AF",
                "country_code" => "CV",
                "country_name" => "Cape Verde",
                "alpha_3" => "CPV",
                "phone_code" => "238",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "continent_code" => "NA",
                "country_code" => "KY",
                "country_name" => "Cayman Islands",
                "alpha_3" => "CYM",
                "phone_code" => "1345",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "continent_code" => "AF",
                "country_code" => "CF",
                "country_name" => "Central African Republic",
                "alpha_3" => "CAF",
                "phone_code" => "236",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "continent_code" => "AF",
                "country_code" => "TD",
                "country_name" => "Chad",
                "alpha_3" => "TCD",
                "phone_code" => "235",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "continent_code" => "SA",
                "country_code" => "CL",
                "country_name" => "Chile",
                "alpha_3" => "CHL",
                "phone_code" => "56",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "continent_code" => "AS",
                "country_code" => "CN",
                "country_name" => "China",
                "alpha_3" => "CHN",
                "phone_code" => "86",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "continent_code" => "AS",
                "country_code" => "CX",
                "country_name" => "Christmas Island",
                "alpha_3" => "CXR",
                "phone_code" => "61",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "continent_code" => "AS",
                "country_code" => "CC",
                "country_name" => "Cocos (Keeling) Islands",
                "alpha_3" => "CCK",
                "phone_code" => "672",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "continent_code" => "SA",
                "country_code" => "CO",
                "country_name" => "Colombia",
                "alpha_3" => "COL",
                "phone_code" => "57",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "continent_code" => "AF",
                "country_code" => "KM",
                "country_name" => "Comoros",
                "alpha_3" => "COM",
                "phone_code" => "269",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "continent_code" => "AF",
                "country_code" => "CG",
                "country_name" => "Congo",
                "alpha_3" => "COG",
                "phone_code" => "242",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "continent_code" => "AF",
                "country_code" => "CD",
                "country_name" => "Congo, Democratic Republic of the Congo",
                "alpha_3" => "COD",
                "phone_code" => "242",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "continent_code" => "OC",
                "country_code" => "CK",
                "country_name" => "Cook Islands",
                "alpha_3" => "COK",
                "phone_code" => "682",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "continent_code" => "NA",
                "country_code" => "CR",
                "country_name" => "Costa Rica",
                "alpha_3" => "CRI",
                "phone_code" => "506",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 55,
                "continent_code" => "AF",
                "country_code" => "CI",
                "country_name" => "Cote D'Ivoire",
                "alpha_3" => "CIV",
                "phone_code" => "225",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 56,
                "continent_code" => "EU",
                "country_code" => "HR",
                "country_name" => "Croatia",
                "alpha_3" => "HRV",
                "phone_code" => "385",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 57,
                "continent_code" => "NA",
                "country_code" => "CU",
                "country_name" => "Cuba",
                "alpha_3" => "CUB",
                "phone_code" => "53",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 58,
                "continent_code" => "NA",
                "country_code" => "CW",
                "country_name" => "Curacao",
                "alpha_3" => "CUW",
                "phone_code" => "599",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 59,
                "continent_code" => "AS",
                "country_code" => "CY",
                "country_name" => "Cyprus",
                "alpha_3" => "CYP",
                "phone_code" => "357",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 60,
                "continent_code" => "EU",
                "country_code" => "CZ",
                "country_name" => "Czech Republic",
                "alpha_3" => "CZE",
                "phone_code" => "420",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 61,
                "continent_code" => "EU",
                "country_code" => "DK",
                "country_name" => "Denmark",
                "alpha_3" => "DNK",
                "phone_code" => "45",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 62,
                "continent_code" => "AF",
                "country_code" => "DJ",
                "country_name" => "Djibouti",
                "alpha_3" => "DJI",
                "phone_code" => "253",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 63,
                "continent_code" => "NA",
                "country_code" => "DM",
                "country_name" => "Dominica",
                "alpha_3" => "DMA",
                "phone_code" => "1767",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 64,
                "continent_code" => "NA",
                "country_code" => "DO",
                "country_name" => "Dominican Republic",
                "alpha_3" => "DOM",
                "phone_code" => "1809",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 65,
                "continent_code" => "SA",
                "country_code" => "EC",
                "country_name" => "Ecuador",
                "alpha_3" => "ECU",
                "phone_code" => "593",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 66,
                "continent_code" => "AF",
                "country_code" => "EG",
                "country_name" => "Egypt",
                "alpha_3" => "EGY",
                "phone_code" => "20",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 67,
                "continent_code" => "NA",
                "country_code" => "SV",
                "country_name" => "El Salvador",
                "alpha_3" => "SLV",
                "phone_code" => "503",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 68,
                "continent_code" => "AF",
                "country_code" => "GQ",
                "country_name" => "Equatorial Guinea",
                "alpha_3" => "GNQ",
                "phone_code" => "240",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 69,
                "continent_code" => "AF",
                "country_code" => "ER",
                "country_name" => "Eritrea",
                "alpha_3" => "ERI",
                "phone_code" => "291",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 70,
                "continent_code" => "EU",
                "country_code" => "EE",
                "country_name" => "Estonia",
                "alpha_3" => "EST",
                "phone_code" => "372",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 71,
                "continent_code" => "AF",
                "country_code" => "ET",
                "country_name" => "Ethiopia",
                "alpha_3" => "ETH",
                "phone_code" => "251",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 72,
                "continent_code" => "SA",
                "country_code" => "FK",
                "country_name" => "Falkland Islands (Malvinas)",
                "alpha_3" => "FLK",
                "phone_code" => "500",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 73,
                "continent_code" => "EU",
                "country_code" => "FO",
                "country_name" => "Faroe Islands",
                "alpha_3" => "FRO",
                "phone_code" => "298",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 74,
                "continent_code" => "OC",
                "country_code" => "FJ",
                "country_name" => "Fiji",
                "alpha_3" => "FJI",
                "phone_code" => "679",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 75,
                "continent_code" => "EU",
                "country_code" => "FI",
                "country_name" => "Finland",
                "alpha_3" => "FIN",
                "phone_code" => "358",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 76,
                "continent_code" => "EU",
                "country_code" => "FR",
                "country_name" => "France",
                "alpha_3" => "FRA",
                "phone_code" => "33",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 77,
                "continent_code" => "SA",
                "country_code" => "GF",
                "country_name" => "French Guiana",
                "alpha_3" => "GUF",
                "phone_code" => "594",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 78,
                "continent_code" => "OC",
                "country_code" => "PF",
                "country_name" => "French Polynesia",
                "alpha_3" => "PYF",
                "phone_code" => "689",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 79,
                "continent_code" => "AN",
                "country_code" => "TF",
                "country_name" => "French Southern Territories",
                "alpha_3" => "ATF",
                "phone_code" => "262",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 80,
                "continent_code" => "AF",
                "country_code" => "GA",
                "country_name" => "Gabon",
                "alpha_3" => "GAB",
                "phone_code" => "241",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 81,
                "continent_code" => "AF",
                "country_code" => "GM",
                "country_name" => "Gambia",
                "alpha_3" => "GMB",
                "phone_code" => "220",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 82,
                "continent_code" => "AS",
                "country_code" => "GE",
                "country_name" => "Georgia",
                "alpha_3" => "GEO",
                "phone_code" => "995",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 83,
                "continent_code" => "EU",
                "country_code" => "DE",
                "country_name" => "Germany",
                "alpha_3" => "DEU",
                "phone_code" => "49",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 84,
                "continent_code" => "AF",
                "country_code" => "GH",
                "country_name" => "Ghana",
                "alpha_3" => "GHA",
                "phone_code" => "233",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 85,
                "continent_code" => "EU",
                "country_code" => "GI",
                "country_name" => "Gibraltar",
                "alpha_3" => "GIB",
                "phone_code" => "350",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 86,
                "continent_code" => "EU",
                "country_code" => "GR",
                "country_name" => "Greece",
                "alpha_3" => "GRC",
                "phone_code" => "30",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 87,
                "continent_code" => "NA",
                "country_code" => "GL",
                "country_name" => "Greenland",
                "alpha_3" => "GRL",
                "phone_code" => "299",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 88,
                "continent_code" => "NA",
                "country_code" => "GD",
                "country_name" => "Grenada",
                "alpha_3" => "GRD",
                "phone_code" => "1473",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 89,
                "continent_code" => "NA",
                "country_code" => "GP",
                "country_name" => "Guadeloupe",
                "alpha_3" => "GLP",
                "phone_code" => "590",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 90,
                "continent_code" => "OC",
                "country_code" => "GU",
                "country_name" => "Guam",
                "alpha_3" => "GUM",
                "phone_code" => "1671",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 91,
                "continent_code" => "NA",
                "country_code" => "GT",
                "country_name" => "Guatemala",
                "alpha_3" => "GTM",
                "phone_code" => "502",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 92,
                "continent_code" => "EU",
                "country_code" => "GG",
                "country_name" => "Guernsey",
                "alpha_3" => "GGY",
                "phone_code" => "44",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 93,
                "continent_code" => "AF",
                "country_code" => "GN",
                "country_name" => "Guinea",
                "alpha_3" => "GIN",
                "phone_code" => "224",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 94,
                "continent_code" => "AF",
                "country_code" => "GW",
                "country_name" => "Guinea-Bissau",
                "alpha_3" => "GNB",
                "phone_code" => "245",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 95,
                "continent_code" => "SA",
                "country_code" => "GY",
                "country_name" => "Guyana",
                "alpha_3" => "GUY",
                "phone_code" => "592",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 96,
                "continent_code" => "NA",
                "country_code" => "HT",
                "country_name" => "Haiti",
                "alpha_3" => "HTI",
                "phone_code" => "509",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 97,
                "continent_code" => "AN",
                "country_code" => "HM",
                "country_name" => "Heard Island and Mcdonald Islands",
                "alpha_3" => "HMD",
                "phone_code" => "0",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 98,
                "continent_code" => "EU",
                "country_code" => "VA",
                "country_name" => "Holy See (Vatican City State)",
                "alpha_3" => "VAT",
                "phone_code" => "39",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 99,
                "continent_code" => "NA",
                "country_code" => "HN",
                "country_name" => "Honduras",
                "alpha_3" => "HND",
                "phone_code" => "504",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 100,
                "continent_code" => "AS",
                "country_code" => "HK",
                "country_name" => "Hong Kong",
                "alpha_3" => "HKG",
                "phone_code" => "852",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 101,
                "continent_code" => "EU",
                "country_code" => "HU",
                "country_name" => "Hungary",
                "alpha_3" => "HUN",
                "phone_code" => "36",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 102,
                "continent_code" => "EU",
                "country_code" => "IS",
                "country_name" => "Iceland",
                "alpha_3" => "ISL",
                "phone_code" => "354",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 103,
                "continent_code" => "AS",
                "country_code" => "IN",
                "country_name" => "India",
                "alpha_3" => "IND",
                "phone_code" => "91",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 104,
                "continent_code" => "AS",
                "country_code" => "ID",
                "country_name" => "Indonesia",
                "alpha_3" => "IDN",
                "phone_code" => "62",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 105,
                "continent_code" => "AS",
                "country_code" => "IR",
                "country_name" => "Iran, Islamic Republic of",
                "alpha_3" => "IRN",
                "phone_code" => "98",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 106,
                "continent_code" => "AS",
                "country_code" => "IQ",
                "country_name" => "Iraq",
                "alpha_3" => "IRQ",
                "phone_code" => "964",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 107,
                "continent_code" => "EU",
                "country_code" => "IE",
                "country_name" => "Ireland",
                "alpha_3" => "IRL",
                "phone_code" => "353",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 108,
                "continent_code" => "EU",
                "country_code" => "IM",
                "country_name" => "Isle of Man",
                "alpha_3" => "IMN",
                "phone_code" => "44",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 109,
                "continent_code" => "AS",
                "country_code" => "IL",
                "country_name" => "Israel",
                "alpha_3" => "ISR",
                "phone_code" => "972",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 110,
                "continent_code" => "EU",
                "country_code" => "IT",
                "country_name" => "Italy",
                "alpha_3" => "ITA",
                "phone_code" => "39",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 111,
                "continent_code" => "NA",
                "country_code" => "JM",
                "country_name" => "Jamaica",
                "alpha_3" => "JAM",
                "phone_code" => "1876",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 112,
                "continent_code" => "AS",
                "country_code" => "JP",
                "country_name" => "Japan",
                "alpha_3" => "JPN",
                "phone_code" => "81",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 113,
                "continent_code" => "EU",
                "country_code" => "JE",
                "country_name" => "Jersey",
                "alpha_3" => "JEY",
                "phone_code" => "44",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 114,
                "continent_code" => "AS",
                "country_code" => "JO",
                "country_name" => "Jordan",
                "alpha_3" => "JOR",
                "phone_code" => "962",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 115,
                "continent_code" => "AS",
                "country_code" => "KZ",
                "country_name" => "Kazakhstan",
                "alpha_3" => "KAZ",
                "phone_code" => "7",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 116,
                "continent_code" => "AF",
                "country_code" => "KE",
                "country_name" => "Kenya",
                "alpha_3" => "KEN",
                "phone_code" => "254",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 117,
                "continent_code" => "OC",
                "country_code" => "KI",
                "country_name" => "Kiribati",
                "alpha_3" => "KIR",
                "phone_code" => "686",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 118,
                "continent_code" => "AS",
                "country_code" => "KP",
                "country_name" => "Korea, Democratic People's Republic of",
                "alpha_3" => "PRK",
                "phone_code" => "850",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 119,
                "continent_code" => "AS",
                "country_code" => "KR",
                "country_name" => "Korea, Republic of",
                "alpha_3" => "KOR",
                "phone_code" => "82",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 120,
                "continent_code" => "EU",
                "country_code" => "XK",
                "country_name" => "Kosovo",
                "alpha_3" => "XKX",
                "phone_code" => "381",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 121,
                "continent_code" => "AS",
                "country_code" => "KW",
                "country_name" => "Kuwait",
                "alpha_3" => "KWT",
                "phone_code" => "965",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 122,
                "continent_code" => "AS",
                "country_code" => "KG",
                "country_name" => "Kyrgyzstan",
                "alpha_3" => "KGZ",
                "phone_code" => "996",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 123,
                "continent_code" => "AS",
                "country_code" => "LA",
                "country_name" => "Lao People's Democratic Republic",
                "alpha_3" => "LAO",
                "phone_code" => "856",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 124,
                "continent_code" => "EU",
                "country_code" => "LV",
                "country_name" => "Latvia",
                "alpha_3" => "LVA",
                "phone_code" => "371",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 125,
                "continent_code" => "AS",
                "country_code" => "LB",
                "country_name" => "Lebanon",
                "alpha_3" => "LBN",
                "phone_code" => "961",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 126,
                "continent_code" => "AF",
                "country_code" => "LS",
                "country_name" => "Lesotho",
                "alpha_3" => "LSO",
                "phone_code" => "266",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 127,
                "continent_code" => "AF",
                "country_code" => "LR",
                "country_name" => "Liberia",
                "alpha_3" => "LBR",
                "phone_code" => "231",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 128,
                "continent_code" => "AF",
                "country_code" => "LY",
                "country_name" => "Libyan Arab Jamahiriya",
                "alpha_3" => "LBY",
                "phone_code" => "218",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 129,
                "continent_code" => "EU",
                "country_code" => "LI",
                "country_name" => "Liechtenstein",
                "alpha_3" => "LIE",
                "phone_code" => "423",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 130,
                "continent_code" => "EU",
                "country_code" => "LT",
                "country_name" => "Lithuania",
                "alpha_3" => "LTU",
                "phone_code" => "370",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 131,
                "continent_code" => "EU",
                "country_code" => "LU",
                "country_name" => "Luxembourg",
                "alpha_3" => "LUX",
                "phone_code" => "352",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 132,
                "continent_code" => "AS",
                "country_code" => "MO",
                "country_name" => "Macao",
                "alpha_3" => "MAC",
                "phone_code" => "853",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 133,
                "continent_code" => "EU",
                "country_code" => "MK",
                "country_name" => "Macedonia, the Former Yugoslav Republic of",
                "alpha_3" => "MKD",
                "phone_code" => "389",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 134,
                "continent_code" => "AF",
                "country_code" => "MG",
                "country_name" => "Madagascar",
                "alpha_3" => "MDG",
                "phone_code" => "261",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 135,
                "continent_code" => "AF",
                "country_code" => "MW",
                "country_name" => "Malawi",
                "alpha_3" => "MWI",
                "phone_code" => "265",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 136,
                "continent_code" => "AS",
                "country_code" => "MY",
                "country_name" => "Malaysia",
                "alpha_3" => "MYS",
                "phone_code" => "60",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 137,
                "continent_code" => "AS",
                "country_code" => "MV",
                "country_name" => "Maldives",
                "alpha_3" => "MDV",
                "phone_code" => "960",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 138,
                "continent_code" => "AF",
                "country_code" => "ML",
                "country_name" => "Mali",
                "alpha_3" => "MLI",
                "phone_code" => "223",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 139,
                "continent_code" => "EU",
                "country_code" => "MT",
                "country_name" => "Malta",
                "alpha_3" => "MLT",
                "phone_code" => "356",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 140,
                "continent_code" => "OC",
                "country_code" => "MH",
                "country_name" => "Marshall Islands",
                "alpha_3" => "MHL",
                "phone_code" => "692",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 141,
                "continent_code" => "NA",
                "country_code" => "MQ",
                "country_name" => "Martinique",
                "alpha_3" => "MTQ",
                "phone_code" => "596",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 142,
                "continent_code" => "AF",
                "country_code" => "MR",
                "country_name" => "Mauritania",
                "alpha_3" => "MRT",
                "phone_code" => "222",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 143,
                "continent_code" => "AF",
                "country_code" => "MU",
                "country_name" => "Mauritius",
                "alpha_3" => "MUS",
                "phone_code" => "230",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 144,
                "continent_code" => "AF",
                "country_code" => "YT",
                "country_name" => "Mayotte",
                "alpha_3" => "MYT",
                "phone_code" => "269",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 145,
                "continent_code" => "NA",
                "country_code" => "MX",
                "country_name" => "Mexico",
                "alpha_3" => "MEX",
                "phone_code" => "52",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 146,
                "continent_code" => "OC",
                "country_code" => "FM",
                "country_name" => "Micronesia, Federated States of",
                "alpha_3" => "FSM",
                "phone_code" => "691",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 147,
                "continent_code" => "EU",
                "country_code" => "MD",
                "country_name" => "Moldova, Republic of",
                "alpha_3" => "MDA",
                "phone_code" => "373",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 148,
                "continent_code" => "EU",
                "country_code" => "MC",
                "country_name" => "Monaco",
                "alpha_3" => "MCO",
                "phone_code" => "377",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 149,
                "continent_code" => "AS",
                "country_code" => "MN",
                "country_name" => "Mongolia",
                "alpha_3" => "MNG",
                "phone_code" => "976",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 150,
                "continent_code" => "EU",
                "country_code" => "ME",
                "country_name" => "Montenegro",
                "alpha_3" => "MNE",
                "phone_code" => "382",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 151,
                "continent_code" => "NA",
                "country_code" => "MS",
                "country_name" => "Montserrat",
                "alpha_3" => "MSR",
                "phone_code" => "1664",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 152,
                "continent_code" => "AF",
                "country_code" => "MA",
                "country_name" => "Morocco",
                "alpha_3" => "MAR",
                "phone_code" => "212",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 153,
                "continent_code" => "AF",
                "country_code" => "MZ",
                "country_name" => "Mozambique",
                "alpha_3" => "MOZ",
                "phone_code" => "258",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 154,
                "continent_code" => "AS",
                "country_code" => "MM",
                "country_name" => "Myanmar",
                "alpha_3" => "MMR",
                "phone_code" => "95",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 155,
                "continent_code" => "AF",
                "country_code" => "NA",
                "country_name" => "Namibia",
                "alpha_3" => "NAM",
                "phone_code" => "264",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 156,
                "continent_code" => "OC",
                "country_code" => "NR",
                "country_name" => "Nauru",
                "alpha_3" => "NRU",
                "phone_code" => "674",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 157,
                "continent_code" => "AS",
                "country_code" => "NP",
                "country_name" => "Nepal",
                "alpha_3" => "NPL",
                "phone_code" => "977",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 158,
                "continent_code" => "EU",
                "country_code" => "NL",
                "country_name" => "Netherlands",
                "alpha_3" => "NLD",
                "phone_code" => "31",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 159,
                "continent_code" => "NA",
                "country_code" => "AN",
                "country_name" => "Netherlands Antilles",
                "alpha_3" => "ANT",
                "phone_code" => "599",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 160,
                "continent_code" => "OC",
                "country_code" => "NC",
                "country_name" => "New Caledonia",
                "alpha_3" => "NCL",
                "phone_code" => "687",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 161,
                "continent_code" => "OC",
                "country_code" => "NZ",
                "country_name" => "New Zealand",
                "alpha_3" => "NZL",
                "phone_code" => "64",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 162,
                "continent_code" => "NA",
                "country_code" => "NI",
                "country_name" => "Nicaragua",
                "alpha_3" => "NIC",
                "phone_code" => "505",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 163,
                "continent_code" => "AF",
                "country_code" => "NE",
                "country_name" => "Niger",
                "alpha_3" => "NER",
                "phone_code" => "227",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 164,
                "continent_code" => "AF",
                "country_code" => "NG",
                "country_name" => "Nigeria",
                "alpha_3" => "NGA",
                "phone_code" => "234",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 165,
                "continent_code" => "OC",
                "country_code" => "NU",
                "country_name" => "Niue",
                "alpha_3" => "NIU",
                "phone_code" => "683",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 166,
                "continent_code" => "OC",
                "country_code" => "NF",
                "country_name" => "Norfolk Island",
                "alpha_3" => "NFK",
                "phone_code" => "672",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 167,
                "continent_code" => "OC",
                "country_code" => "MP",
                "country_name" => "Northern Mariana Islands",
                "alpha_3" => "MNP",
                "phone_code" => "1670",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 168,
                "continent_code" => "EU",
                "country_code" => "NO",
                "country_name" => "Norway",
                "alpha_3" => "NOR",
                "phone_code" => "47",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 169,
                "continent_code" => "AS",
                "country_code" => "OM",
                "country_name" => "Oman",
                "alpha_3" => "OMN",
                "phone_code" => "968",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 170,
                "continent_code" => "AS",
                "country_code" => "PK",
                "country_name" => "Pakistan",
                "alpha_3" => "PAK",
                "phone_code" => "92",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 171,
                "continent_code" => "OC",
                "country_code" => "PW",
                "country_name" => "Palau",
                "alpha_3" => "PLW",
                "phone_code" => "680",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 172,
                "continent_code" => "AS",
                "country_code" => "PS",
                "country_name" => "Palestinian Territory, Occupied",
                "alpha_3" => "PSE",
                "phone_code" => "970",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 173,
                "continent_code" => "NA",
                "country_code" => "PA",
                "country_name" => "Panama",
                "alpha_3" => "PAN",
                "phone_code" => "507",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 174,
                "continent_code" => "OC",
                "country_code" => "PG",
                "country_name" => "Papua New Guinea",
                "alpha_3" => "PNG",
                "phone_code" => "675",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 175,
                "continent_code" => "SA",
                "country_code" => "PY",
                "country_name" => "Paraguay",
                "alpha_3" => "PRY",
                "phone_code" => "595",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 176,
                "continent_code" => "SA",
                "country_code" => "PE",
                "country_name" => "Peru",
                "alpha_3" => "PER",
                "phone_code" => "51",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 177,
                "continent_code" => "AS",
                "country_code" => "PH",
                "country_name" => "Philippines",
                "alpha_3" => "PHL",
                "phone_code" => "63",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 178,
                "continent_code" => "OC",
                "country_code" => "PN",
                "country_name" => "Pitcairn",
                "alpha_3" => "PCN",
                "phone_code" => "64",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 179,
                "continent_code" => "EU",
                "country_code" => "PL",
                "country_name" => "Poland",
                "alpha_3" => "POL",
                "phone_code" => "48",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 180,
                "continent_code" => "EU",
                "country_code" => "PT",
                "country_name" => "Portugal",
                "alpha_3" => "PRT",
                "phone_code" => "351",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 181,
                "continent_code" => "NA",
                "country_code" => "PR",
                "country_name" => "Puerto Rico",
                "alpha_3" => "PRI",
                "phone_code" => "1787",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 182,
                "continent_code" => "AS",
                "country_code" => "QA",
                "country_name" => "Qatar",
                "alpha_3" => "QAT",
                "phone_code" => "974",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 183,
                "continent_code" => "AF",
                "country_code" => "RE",
                "country_name" => "Reunion",
                "alpha_3" => "REU",
                "phone_code" => "262",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 184,
                "continent_code" => "EU",
                "country_code" => "RO",
                "country_name" => "Romania",
                "alpha_3" => "ROM",
                "phone_code" => "40",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 185,
                "continent_code" => "AS",
                "country_code" => "RU",
                "country_name" => "Russian Federation",
                "alpha_3" => "RUS",
                "phone_code" => "70",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 186,
                "continent_code" => "AF",
                "country_code" => "RW",
                "country_name" => "Rwanda",
                "alpha_3" => "RWA",
                "phone_code" => "250",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 187,
                "continent_code" => "NA",
                "country_code" => "BL",
                "country_name" => "Saint Barthelemy",
                "alpha_3" => "BLM",
                "phone_code" => "590",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 188,
                "continent_code" => "AF",
                "country_code" => "SH",
                "country_name" => "Saint Helena",
                "alpha_3" => "SHN",
                "phone_code" => "290",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 189,
                "continent_code" => "NA",
                "country_code" => "KN",
                "country_name" => "Saint Kitts and Nevis",
                "alpha_3" => "KNA",
                "phone_code" => "1869",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 190,
                "continent_code" => "NA",
                "country_code" => "LC",
                "country_name" => "Saint Lucia",
                "alpha_3" => "LCA",
                "phone_code" => "1758",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 191,
                "continent_code" => "NA",
                "country_code" => "MF",
                "country_name" => "Saint Martin",
                "alpha_3" => "MAF",
                "phone_code" => "590",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 192,
                "continent_code" => "NA",
                "country_code" => "PM",
                "country_name" => "Saint Pierre and Miquelon",
                "alpha_3" => "SPM",
                "phone_code" => "508",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 193,
                "continent_code" => "NA",
                "country_code" => "VC",
                "country_name" => "Saint Vincent and the Grenadines",
                "alpha_3" => "VCT",
                "phone_code" => "1784",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 194,
                "continent_code" => "OC",
                "country_code" => "WS",
                "country_name" => "Samoa",
                "alpha_3" => "WSM",
                "phone_code" => "684",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 195,
                "continent_code" => "EU",
                "country_code" => "SM",
                "country_name" => "San Marino",
                "alpha_3" => "SMR",
                "phone_code" => "378",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 196,
                "continent_code" => "AF",
                "country_code" => "ST",
                "country_name" => "Sao Tome and Principe",
                "alpha_3" => "STP",
                "phone_code" => "239",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 197,
                "continent_code" => "AS",
                "country_code" => "SA",
                "country_name" => "Saudi Arabia",
                "alpha_3" => "SAU",
                "phone_code" => "966",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 198,
                "continent_code" => "AF",
                "country_code" => "SN",
                "country_name" => "Senegal",
                "alpha_3" => "SEN",
                "phone_code" => "221",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 199,
                "continent_code" => "EU",
                "country_code" => "RS",
                "country_name" => "Serbia",
                "alpha_3" => "SRB",
                "phone_code" => "381",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 200,
                "continent_code" => "EU",
                "country_code" => "CS",
                "country_name" => "Serbia and Montenegro",
                "alpha_3" => "SCG",
                "phone_code" => "381",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 201,
                "continent_code" => "AF",
                "country_code" => "SC",
                "country_name" => "Seychelles",
                "alpha_3" => "SYC",
                "phone_code" => "248",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 202,
                "continent_code" => "AF",
                "country_code" => "SL",
                "country_name" => "Sierra Leone",
                "alpha_3" => "SLE",
                "phone_code" => "232",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 203,
                "continent_code" => "AS",
                "country_code" => "SG",
                "country_name" => "Singapore",
                "alpha_3" => "SGP",
                "phone_code" => "65",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 204,
                "continent_code" => "NA",
                "country_code" => "SX",
                "country_name" => "Sint Maarten",
                "alpha_3" => "SXM",
                "phone_code" => "1",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 205,
                "continent_code" => "EU",
                "country_code" => "SK",
                "country_name" => "Slovakia",
                "alpha_3" => "SVK",
                "phone_code" => "421",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 206,
                "continent_code" => "EU",
                "country_code" => "SI",
                "country_name" => "Slovenia",
                "alpha_3" => "SVN",
                "phone_code" => "386",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 207,
                "continent_code" => "OC",
                "country_code" => "SB",
                "country_name" => "Solomon Islands",
                "alpha_3" => "SLB",
                "phone_code" => "677",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 208,
                "continent_code" => "AF",
                "country_code" => "SO",
                "country_name" => "Somalia",
                "alpha_3" => "SOM",
                "phone_code" => "252",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 209,
                "continent_code" => "AF",
                "country_code" => "ZA",
                "country_name" => "South Africa",
                "alpha_3" => "ZAF",
                "phone_code" => "27",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 210,
                "continent_code" => "AN",
                "country_code" => "GS",
                "country_name" => "South Georgia and the South Sandwich Islands",
                "alpha_3" => "SGS",
                "phone_code" => "500",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 211,
                "continent_code" => "AF",
                "country_code" => "SS",
                "country_name" => "South Sudan",
                "alpha_3" => "SSD",
                "phone_code" => "211",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 212,
                "continent_code" => "EU",
                "country_code" => "ES",
                "country_name" => "Spain",
                "alpha_3" => "ESP",
                "phone_code" => "34",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 213,
                "continent_code" => "AS",
                "country_code" => "LK",
                "country_name" => "Sri Lanka",
                "alpha_3" => "LKA",
                "phone_code" => "94",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 214,
                "continent_code" => "AF",
                "country_code" => "SD",
                "country_name" => "Sudan",
                "alpha_3" => "SDN",
                "phone_code" => "249",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 215,
                "continent_code" => "SA",
                "country_code" => "SR",
                "country_name" => "Suriname",
                "alpha_3" => "SUR",
                "phone_code" => "597",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 216,
                "continent_code" => "EU",
                "country_code" => "SJ",
                "country_name" => "Svalbard and Jan Mayen",
                "alpha_3" => "SJM",
                "phone_code" => "47",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 217,
                "continent_code" => "AF",
                "country_code" => "SZ",
                "country_name" => "Swaziland",
                "alpha_3" => "SWZ",
                "phone_code" => "268",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 218,
                "continent_code" => "EU",
                "country_code" => "SE",
                "country_name" => "Sweden",
                "alpha_3" => "SWE",
                "phone_code" => "46",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 219,
                "continent_code" => "EU",
                "country_code" => "CH",
                "country_name" => "Switzerland",
                "alpha_3" => "CHE",
                "phone_code" => "41",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 220,
                "continent_code" => "AS",
                "country_code" => "SY",
                "country_name" => "Syrian Arab Republic",
                "alpha_3" => "SYR",
                "phone_code" => "963",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 221,
                "continent_code" => "AS",
                "country_code" => "TW",
                "country_name" => "Taiwan, Province of China",
                "alpha_3" => "TWN",
                "phone_code" => "886",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 222,
                "continent_code" => "AS",
                "country_code" => "TJ",
                "country_name" => "Tajikistan",
                "alpha_3" => "TJK",
                "phone_code" => "992",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 223,
                "continent_code" => "AF",
                "country_code" => "TZ",
                "country_name" => "Tanzania, United Republic of",
                "alpha_3" => "TZA",
                "phone_code" => "255",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 224,
                "continent_code" => "AS",
                "country_code" => "TH",
                "country_name" => "Thailand",
                "alpha_3" => "THA",
                "phone_code" => "66",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 225,
                "continent_code" => "AS",
                "country_code" => "TL",
                "country_name" => "Timor-Leste",
                "alpha_3" => "TLS",
                "phone_code" => "670",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 226,
                "continent_code" => "AF",
                "country_code" => "TG",
                "country_name" => "Togo",
                "alpha_3" => "TGO",
                "phone_code" => "228",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 227,
                "continent_code" => "OC",
                "country_code" => "TK",
                "country_name" => "Tokelau",
                "alpha_3" => "TKL",
                "phone_code" => "690",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 228,
                "continent_code" => "OC",
                "country_code" => "TO",
                "country_name" => "Tonga",
                "alpha_3" => "TON",
                "phone_code" => "676",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 229,
                "continent_code" => "NA",
                "country_code" => "TT",
                "country_name" => "Trinidad and Tobago",
                "alpha_3" => "TTO",
                "phone_code" => "1868",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 230,
                "continent_code" => "AF",
                "country_code" => "TN",
                "country_name" => "Tunisia",
                "alpha_3" => "TUN",
                "phone_code" => "216",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 231,
                "continent_code" => "AS",
                "country_code" => "TR",
                "country_name" => "Turkey",
                "alpha_3" => "TUR",
                "phone_code" => "90",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 232,
                "continent_code" => "AS",
                "country_code" => "TM",
                "country_name" => "Turkmenistan",
                "alpha_3" => "TKM",
                "phone_code" => "7370",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 233,
                "continent_code" => "NA",
                "country_code" => "TC",
                "country_name" => "Turks and Caicos Islands",
                "alpha_3" => "TCA",
                "phone_code" => "1649",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 234,
                "continent_code" => "OC",
                "country_code" => "TV",
                "country_name" => "Tuvalu",
                "alpha_3" => "TUV",
                "phone_code" => "688",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 235,
                "continent_code" => "AF",
                "country_code" => "UG",
                "country_name" => "Uganda",
                "alpha_3" => "UGA",
                "phone_code" => "256",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 236,
                "continent_code" => "EU",
                "country_code" => "UA",
                "country_name" => "Ukraine",
                "alpha_3" => "UKR",
                "phone_code" => "380",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 237,
                "continent_code" => "AS",
                "country_code" => "AE",
                "country_name" => "United Arab Emirates",
                "alpha_3" => "ARE",
                "phone_code" => "971",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 238,
                "continent_code" => "EU",
                "country_code" => "GB",
                "country_name" => "United Kingdom",
                "alpha_3" => "GBR",
                "phone_code" => "44",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 239,
                "continent_code" => "NA",
                "country_code" => "US",
                "country_name" => "United States",
                "alpha_3" => "USA",
                "phone_code" => "1",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 240,
                "continent_code" => "NA",
                "country_code" => "UM",
                "country_name" => "United States Minor Outlying Islands",
                "alpha_3" => "UMI",
                "phone_code" => "1",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 241,
                "continent_code" => "SA",
                "country_code" => "UY",
                "country_name" => "Uruguay",
                "alpha_3" => "URY",
                "phone_code" => "598",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 242,
                "continent_code" => "AS",
                "country_code" => "UZ",
                "country_name" => "Uzbekistan",
                "alpha_3" => "UZB",
                "phone_code" => "998",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 243,
                "continent_code" => "OC",
                "country_code" => "VU",
                "country_name" => "Vanuatu",
                "alpha_3" => "VUT",
                "phone_code" => "678",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 244,
                "continent_code" => "SA",
                "country_code" => "VE",
                "country_name" => "Venezuela",
                "alpha_3" => "VEN",
                "phone_code" => "58",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 245,
                "continent_code" => "AS",
                "country_code" => "VN",
                "country_name" => "Viet Nam",
                "alpha_3" => "VNM",
                "phone_code" => "84",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 246,
                "continent_code" => "NA",
                "country_code" => "VG",
                "country_name" => "Virgin Islands, British",
                "alpha_3" => "VGB",
                "phone_code" => "1284",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 247,
                "continent_code" => "NA",
                "country_code" => "VI",
                "country_name" => "Virgin Islands, U.s.",
                "alpha_3" => "VIR",
                "phone_code" => "1340",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 248,
                "continent_code" => "OC",
                "country_code" => "WF",
                "country_name" => "Wallis and Futuna",
                "alpha_3" => "WLF",
                "phone_code" => "681",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 249,
                "continent_code" => "AF",
                "country_code" => "EH",
                "country_name" => "Western Sahara",
                "alpha_3" => "ESH",
                "phone_code" => "212",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 250,
                "continent_code" => "AS",
                "country_code" => "YE",
                "country_name" => "Yemen",
                "alpha_3" => "YEM",
                "phone_code" => "967",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 251,
                "continent_code" => "AF",
                "country_code" => "ZM",
                "country_name" => "Zambia",
                "alpha_3" => "ZMB",
                "phone_code" => "260",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 252,
                "continent_code" => "AF",
                "country_code" => "ZW",
                "country_name" => "Zimbabwe",
                "alpha_3" => "ZWE",
                "phone_code" => "263",
                "available" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );

        foreach($countries as $country){
            Country::create($country);
        }

    }
}
